language: python
dist: xenial
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8-dev
    - pypy
    - pypy3
install:
    - pip install .
script:
    - python setup.py test -q
notifications:
    email: false
