language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy
    - pypy3
install:
    - pip install . --use-mirrors
script:
    - python setup.py test -q
notifications:
    email: false
